name: snakepipes_Hi-C 
channels:
  - r
  - bioconda
  - conda-forge
  - microsoft
  - defaults
dependencies:
  - bcftools
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - bioconductor-biocparallel
  - bioconductor-biostrings
  - bioconductor-delayedarray
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-rhtslib
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - bowtie2
  - bzip2
  - cooler
  - curl
  - cycler
  - cytoolz
  - dataclasses
  - freetype
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - hic2cool
  - hicexplorer
  - hicmatrix
  - htslib
  - httplib2
  - humanfriendly
  - hyperopt
  - iced
  - icu
  - idna
  - imbalanced-learn
  - markdown
  - markupsafe
  - matplotlib
  - mock
  - mpi
  - mpi4py
  - mpich
  - msgpack-python
  - multidict
  - multiprocess
  - multiqc
  - ncurses
  - numpy
  - olefile
  - openjdk=8.0
  - openjpeg
  - openssl
  - packaging
  - pairix
  - pandas
  - pango
  - paramiko
  - parso
  - partd
  - pcre
  - pcre2
  - peppy
  - perl
  - pexpect
  - pickleshare
  - pillow
  - pixman
  - pkgutil-resolve-name
  - plac
  - platformdirs
  - pluggy
  - ply
  - prettytable
  - prompt-toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pulp
  - pure_eval
  - py4j
  - pyasn1
  - pyasn1-modules
  - pybedtools
  - pybigwig
  - pybind11
  - pybind11-global
  - pycparser
  - pyfaidx
  - pygenometracks
  - pygments
  - pynacl
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysam
  - pysftp
  - pysocks
  - pytables
  - python
  - pytz
  - pyu2f
  - pyyaml
  - pyzmq
  - r-base
  - r-ggplot2
  - r-glue
  - r-rcolorbrewer
  - r-readr
  - r-readxl
  - r-stringr
  - readline
  - samtools
  - scikit-learn
  - scipy
  - setuptools
  - six
  - tk
  - tktable
  - tqdm
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
